### PR TITLE
Evaluation functions

### LINKED ISSUE #83: Add automatic scoring functionality for evaluation
To aid automatic evaluation, we could add functionality where we pass in a function which takes in a completed `prompt_dict` (i.e. one with "response" key) and returns some sort of "score" or "evaluation".

This function could for instance compute some sort of string or pattern matching to an "expected" key in the `prompt_dict`.

I'm thinking for the CLI, this could mean passing in some sort of python script with an scorer/evaluation function that is computed on each line of the output JSONL file.

### PR DESCRIPTION
**Pull request by EdwinB12**
Very simple application of using an evaluation function in prompto.

### CODE REVIEW

**Comment by EdwinB12** [comment]
This would work better as a method in experiment. The user would run it outside of experiment.process()

**Comment by EdwinB12** [comment]
Restriction on passed function is it must take in a prompt dictionary and it must return a prompt dictionary

**Comment by EdwinB12** [comment]
Should support a list/tuple of functions. Don't support arguments. Encourage the user to use the prompt dictionary to parameterise.

**Comment by EdwinB12** [comment]
This has ended up being a very bare bones application of this and i'm not sure what value it actually adds over just running an evaluation function on the completed responses dictionary saved to disk after called `.process()`.

**Review by rchan26 — APPROVED** [review]
thanks @EdwinB12 - looks great! this will definitely be useful in practice since having to manually post-run an evaluation on responses is not ideal. in the future, this will be a CLI command like the judge one

will merge this and I will add documentation pages for this

**Pull request merged**
